# Generated by Django 5.0.4 on 2024-06-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_usercourseprogress_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourseProgress',
        ),
    ]
