# Generated by Django 5.0.4 on 2024-06-15 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_progress_course_step_progress_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.course'),
        ),
    ]
